# Generated by Django 5.0 on 2024-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_alter_language_name_alter_technology_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
